### ISSUE TITLE
Question about AF-AudioSet.json

### ISSUE THREAD

**Issue by Mu-Y** [NVIDIA/audio-flamingo#10]
Hello,

Thanks for providing Audioset captionized by the AF chat model. In AF-AudioSet.json, why there are duplicated ytids? It seems like different captions for the same ytids are also slightly different in terms of the mentioned audio events.

Thanks,
Mu

**Comment by zhifengkongnv** [comment]
We pick top-3 captions with the highest clap scores, so each ytid can have up to 3 captions.

**Comment by Mu-Y** [comment]
For ytids with multiple captions, are these captions in the order of highest clap score to lowest clap score? Thanks!

**Comment by zhifengkongnv** [comment]
I think they might be in the random order. You could run laion-clap to get the clap similarity between audio and caption.
See here: 
https://github.com/LAION-AI/CLAP?tab=readme-ov-file#quick-start
We used the 630k-audioset-fusion-best model.
