### ISSUE TITLE
On the Access of Pre-trained Checkpoints

### ISSUE THREAD

**Issue by nicolaus625** [NVIDIA/audio-flamingo#15]
Which specific pre-trained Laion-CLAP checkpoints [website](https://huggingface.co/lukewys/laion_clap/tree/main) did you use for model development?

And which MS-CLAP pre-trained checkpoint did you use?

I tried several of them, but none of them works in the following code
> model_state_dict = torch.load(self.model_fp, map_location=torch.device('cpu'))['state_dict']
> clapcap.load_state_dict(model_state_dict)

**Comment by zhifengkongnv** [comment]
laion clap: 630k-fusion-best
ms clap: clapcap
The pretrained checkpoints use msclap - clapcap. 
msclap code is quite sensitive to huggingface transformers version. IIRC transformers=4.27.4 or 4.28.1 should work.
