### ISSUE TITLE
Checkpoint release time.

### ISSUE THREAD

**Issue by ttgeng233** [NVIDIA/audio-flamingo#2]
Hi, thank you very much for your excellent work. 

I found the checkpoint of the model was not provided: "checkpoint_path = "./audio-flamingo/assets/audio-flamingo-data/checkpoint/foundation_sft_no_ICL/checkpoint_99.pt"

I am wondering when will it be released?  Looking forward to your reply!

**Comment by zhifengkongnv** [comment]
The checkpoints are now released :)
