### ISSUE TITLE
Problem with downloading the checkpoints

### ISSUE THREAD

**Issue by SaraAlthubaiti** [NVIDIA/audio-flamingo#3]
Thanks for uploading the checkpoints, when I tried to download any of them; I'm getting this error (even with normal way (i.e., not wget, curl, or so on)).

Any advice?

<img width="503" alt="Screenshot 2024-07-01 at 5 33 52 PM" src="https://github.com/NVIDIA/audio-flamingo/assets/31218142/37a3af0a-71f7-44e8-a52b-2cede9f87397">

Very nice work and I'm eager to try it :)

**Comment by Sadeen** [comment]
I faced same issue. any solution please ?

**Comment by zhifengkongnv** [comment]
did you use git lfs?

**Comment by SoshyHayami** [comment]
sorry, why not just uploading them to hugging face?

**Comment by zhifengkongnv** [comment]
working on it

**Comment by zhifengkongnv** [comment]
Checkpoints are now on huggingface. Git lfs is still needed but the checkpoints are not separated in chunks anymore. 
https://huggingface.co/nvidia/audio-flamingo

**Comment by SaraAlthubaiti** [comment]
> did you use git lfs?

I tried it as it was the first thing came to my mind but surprisingly it's not, but thanks a lot for uploading it to huggingface; that's much better 🥳
