### ISSUE TITLE
Correct evaluation for freeform output

### ISSUE THREAD

**Issue by jasonppy** [NVIDIA/audio-flamingo#5]
Thanks for the great work and open sourcing the code and weights!

In an attempt to reproduce the evaluation results, I notice that the model's freeform output doesn't always follow expected format. For example, for clotho binary questions, the expected output should be just "yes" or "no", but the model's output can be "yes, {some explanation}" or sometimes even not outputting "yes" or "no".

According to the paper - "Note we use free-form text output to evaluate our model at all times." I'm assuming only exact string-level match should be counted as correct, and if that's the case, the accuracy on clotho would be single digits.

It could be that I used a prompt that's not appropriate:
<img width="485" alt="image" src="https://github.com/user-attachments/assets/c5140131-5165-4672-9110-12dd9537e7a4">

Thanks for your time!

Puyuan

**Comment by zhifengkongnv** [comment]
For Clotho-AQA binary questions (and for the other classification tasks), you should add all options to the input.

For example: 
```
{
    'prefix': 'The task is audio question answering.', 
    'prompt': 'Please answer this question: Are there waves?\nOPTIONS:\nyes.\nno.'
}
```

See here for a few examples
https://github.com/NVIDIA/audio-flamingo/blob/main/inference/inference_examples.py#L170

Another thing is to set the `inference_kwargs`. For benchmark evaluation, we used `temperature=0.0, num_beams=3` and no `do_sample` for less randomness and more stable outputs. These will replace the `do_sample, top_p, and top_k` in the `inference_kwargs` here
https://github.com/NVIDIA/audio-flamingo/blob/main/inference/inference_examples.py#L157
